export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const START_FETCH_PRODUCTS = 'START_FETCH_PRODUCTS';
export const END_FETCH_PRODUCTS = 'END_FETCH_PRODUCTS';
export const SET_DETAIL_STARTING_STYLES = 'SET_DETAIL_STARTING_STYLES';
